@startuml TEDE_InventoryModule

class Supplier

class PurchaseOrder

class Warehouse

class InventoryItem

class StockTransaction

Supplier "1" -- "*" PurchaseOrder
PurchaseOrder "*" -- "*" InventoryItem
Warehouse "1" -- "*" InventoryItem
InventoryItem "1" -- "*" StockTransaction

@enduml